# Experiment Parameters
experiment_name: "Loopgen training"
steps_per_log: 1
train_test_val_splits: [0.85, 0.10, 0.05]
run_name: "translations_only"
checkpoint_outfile: "best_weights"
checkpoint_metric: "validation_loss"
batch_size: 128

# Model Parameters
learning_rate: 0.0001
translation_beta_schedule: "linear"
num_time_steps: 100
min_trans_beta: 0.0001
max_trans_beta: 20
weight_loss_by_norm: True

# DataModule Parameters
fix_cdr_centre: True
self_conditioning_rate: 0.5
add_pad_cdr_features: True

#Output Paths
out_dir: "./translations_only"
