# Experiment Parameters
experiment_name: "Loopgen training"
steps_per_log: 5
run_name: "rotation_quadratic"
checkpoint_metric: "validation_loss"
batch_size: 128
max_epochs: 250

# Model Parameters
learning_rate: 0.0001 # only needed if training
rotation_beta_schedule: "quadratic"
translation_beta_schedule: "linear"
num_time_steps: 100
min_rot_beta: 0.1
max_rot_beta: 1.5
min_trans_beta: 0.0001
max_trans_beta: 20
weight_loss_by_norm: True
use_igso3_cache: False

# DataModule Parameters
fix_cdr_centre: True
self_conditioning_rate: 0.5
add_pad_cdr_features: True

# Output Paths
out_dir: "./rotation_quadratic"
