# Experiment Parameters
experiment_name: "Abdiff training"
steps_per_log: 100
train_test_val_splits: [0.85, 0.10, 0.05]
run_name: "rotation_linear"
checkpoint_outfile: "best_weights"
checkpoint_metric: "validation_loss"
batch_size: 128
max_epochs: 500

# Model Parameters
learning_rate: 0.0001 # only needed if training
rotation_beta_schedule: "linear"
translation_beta_schedule: "linear"
num_time_steps: 100
min_rot_beta: 0.1
max_rot_beta: 1.5
min_trans_beta: 0.0001
max_trans_beta: 20
weight_loss_by_norm: True
use_cache: False

# DataModule Parameters
fix_cdr_centre: True
self_conditioning_rate: 0.5
add_pad_cdr_features: True

# Output Paths
out_dir: "./rotation_linear"
