name: loopgen
channels:
  - conda-forge
  - anaconda
  - pytorch
  - defaults
  - bioconda
dependencies:
  - python=3.11
  - biopython=1.81
  - scipy
  - pyyaml=6.0
  - scikit-learn=1.3.0
  - pandas=2.0.3
  - mlflow=2.5.0
  - numpy
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.16.1
  - jupyter
  - pip
  - einops=0.6.1
  - pytest=7.4.0
  - urllib3=1.26.7

